### ISSUE TITLE
Failed to fetch monitor heartbeats

### ISSUE THREAD

**Issue by boddedo** [KSJaay/Lunalytics#61]
When I created a new monitor, I obtain:
`Failed to fetch monitor heartbeats`
when I press `1 month` view.

**Comment by KSJaay** [comment]
Yeah, this is something I noticed as well but haven't gotten around to fixing yet. Will make some changes around this within 0.7.1 update

**Comment by KSJaay** [comment]
Issue was fixed in PR: https://github.com/KSJaay/Lunalytics/pull/64. Will be closing this now.
